name: Build(1.13.1_py3.9.12_cuda11.7.1_ubuntu20.04_pai_sm35_withcuda)

env:
  BASE_IMAGE: "nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04"

  PYTHON_VERSION: "3.9.12"

  PYTORCH_VERSION: "1.13.1"
  PYTORCH_VERSION_SUFFIX: "+cu117"
  TORCHVISION_VERSION: "0.14.1"
  TORCHVISION_VERSION_SUFFIX: "+cu117"
  TORCHAUDIO_VERSION: "0.13.1"
  TORCHAUDIO_VERSION_SUFFIX: "+cu117"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/cu117/torch_stable.html"
  SM35_PYTORCH_DOWNLOAD_URL: "https://nelsonliu.me/files/pytorch/whl/torch_stable.html"
  IMAGE_TAG: "1.13.1-py3.9.12-cuda11.7.1-ubuntu20.04-pai-sm35-withcuda"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fix permission
        run: chmod -R 777 docker
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build docker image
        run: docker/ubuntu-pai/build.sh
        
      - name: Push docker image
        run: docker push yulonger/pytorch:${IMAGE_TAG}
